name: Latest blog posts workflow
on:
  schedule:
    # Runs once a day at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://w3ird.tech/index.xml"
          max_post_count: 5
          template: "- $date: [$title]($url)"
          date_format: "yyyy-MM-dd"
          committer_email: "rob@w3ird.tech"
          committer_username: "w3irdrobot"
